### ISSUE TITLE
Button style and label does not update when moving window to another workspace

### ISSUE THREAD

**Issue by arngo** [carmanaught/gnome-shell-extension-workspace-buttons#3]
Gnome 3.26.2 running on Arch Linux

When moving a window to another workspace without switching workspaces (i.e. dragging the window in overview mode or selecting "Move to Workspace Down/Up" in the window right click menu) the button does not update to the proper workspace style/label.

**Comment by carmanaught** [comment]
It's great that you're using some of the things that I don't normally use, or use much, that's helping to find these bugs. I very rarely use the "Move to Workspace Up/Down" stuff and usually move my windows with the "move-to-workspace-#" shortcuts I've defined through "dconf-editor"

This fix should solve your issue and also replaces the previous "window-created" signal handler, since they both serve essentially the same purpose.

**Comment by arngo** [comment]
Haha, no problem, and thanks for the great work.

There is still an issue with updating the button when moving a window back out of another workspace, it keeps the inactive styling even when it becomes empty. Is it as simple as copying the signal handler for "window-added" and changing it to "window-removed"?

**Comment by carmanaught** [comment]
For the most part it was just adding the "window-removed" signal, but I also updated the "window-added" signal to not trigger when the window is "on all workspaces" the same way I've done for the now added "window-removed" signal.

The upside of these changes is that windows being created/destroyed shouldn't trigger updates in all buttons now, but only the buttons for which the creation/destruction events happen.

**Comment by arngo** [comment]
Looks good. Once again, thank you for the quick response.
